apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-rule
  namespace: demo
spec:
  host: demo-svc.demo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: website-v1
  - name: v2
    labels:
      version: website-v2
  - name: locust
    labels:
      version: website-locust
